### PR TITLE
Fix: $reviewUrl throws 500 on live workspace

### LINKED ISSUE #4: $reviewUrl throws 500 on live workspace
With activated `$this->settings['notify']['publicWorkspace']` you get notified about changes to the live workspace. 
The generated $reviewUrl throws an error 500, cause you can't show changes on the live workspace. 

**Generated $reviewUrl for a "not-live" Workspace (ex. Preview)**
`/neos/management/workspaces/show?moduleArguments%5Bworkspace%5D%5B__identity%5D=preview-xbpqb`

**Generated $reviewUrl for the "live" Workspace throws an Error 500**
`/neos/management/workspaces/show?moduleArguments[workspace][__identity]=live`

### PR DESCRIPTION
**Pull request by paavo**
Fixes https://github.com/code-q-web-factory/neos-publishnotifier/issues/4

### CODE REVIEW

**Comment by rolandschuetz** [comment]
Hmmm... the message is a bit odd for public workspaces, since it then says:

```
*%1$s* has published changes to the workspace *%2$s*.
Please review the changes and publish to live: [DOMAIN]/neos/management/workspaces/
```

**Comment by rolandschuetz** [comment]
Is this still relevant for you?

**Comment by paavo** [comment]
We stopped using it for review, but we'd use it again if this gets fixed ☝️

**Comment by paavo** [comment]
Oh, i just saw the pushed Message is a bit odd for public workspaces. 
How about a dedicated message for "non-public" workspaces?
So this acts as a "you have to review changes" reminder.

**Comment by rolandschuetz** [comment]
Sure, feel free to adopt the PR and I'll merge it.

**Comment by rolandschuetz** [comment]
@paavo Did you abbandon this?

**Comment by paavo** [comment]
> @paavo Did you abbandon this?

Looks like, sorry 🙈

**Pull request closed without merging**
