### PR TITLE
Added Notifier-Options

### PR DESCRIPTION
**Pull request by paavo**
Added options to enable Notifications for:
- Pushes to the public workspace (live)
- Every Push (instead of the first push to a workspace)

### CODE REVIEW

**Comment by rolandschuetz** [comment]
For consistency, it should also be possible to only get notifications for public workspaces and turn internal workspace pushes off.

**Review by rolandschuetz — CHANGES_REQUESTED** [review]
For consistency, it should also be possible to only get notifications for public workspaces and turn internal workspace pushes off.

`everyChange` is not very clear and only relevant for the internal workspace, maybe split into the following:

```

CodeQ:
  PublishNotifier:
    notify:
      internalWorkspaceWithoutUnpublishedChanges: true # Send notification for publishing to any internal workspace, which has no unpublished changes yet
      internalWorkspaceWithUnpublishedChanges: true # Send notification for publishing to any internal workspace, which already has unpublished changes
      publicWorkspace: false # Send notification for publishing to LIVE Workspace
```

**Comment by paavo** [comment]
thanks @rolandschuetz, i already refactored the Settings

**Comment by rolandschuetz** [comment]
There is still a logical bug, please test all cases before the next push ;)

**Comment by paavo** [comment]
@rolandschuetz looks like there really was a logical bug 🤦‍♂ 
fixed ✔️

**Comment by rolandschuetz** [comment]
@drlimbo Thanks for the pull request. I have merged it.

I have changed the logic to `internalWorkspace.onFirstChange` and `internalWorkspace.onAdditionalChange`:
https://github.com/code-q-web-factory/neos-publishnotifier/commit/ea652681f0d2a3cfe7e5fd669b0f18f2855f6b11

It has been released at v2.2.0
https://github.com/code-q-web-factory/neos-publishnotifier/releases/tag/v2.2.0

**Pull request merged**
